FROM rust:bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    iproute2 iptables procps tcpdump \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /dquic
ENV CARGO_TARGET_DIR=/build
