[package]
name = "qmacro"
version = "0.5.1"
edition.workspace = true
description = "dquic's proc macros"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "3", features = ["full"] }
quote = "1"
