[package]
name = "qtraversal"
workspace = ".."
version = "0.7.2"
edition.workspace = true
description = "NAT traversal utilities for QUIC, a part of dquic"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
bytes.workspace = true
dashmap.workspace = true
qbase.workspace = true
qprotocol = { path = "../qprotocol" }
qtransport = { path = "../qtransport" }
rand.workspace = true
tokio = { workspace = true, features = ["sync", "rt", "time", "macros"] }
tracing.workspace = true

[dev-dependencies]
clap.workspace = true
netdev.workspace = true
qudp.workspace = true
tokio = { workspace = true, features = ["test-util", "rt-multi-thread", "signal"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
test-ttl = []
