[package]
name = "qresolve"
version = "0.8.0-beta.1"
edition.workspace = true
description = "dquic's dns abstractions"
readme.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
dns-lookup = "3"
futures = { workspace = true }
tokio = { workspace = true, features = ["net"] }
qbase = { workspace = true }
