[package]
name = "dquic"
version = "0.8.0"
edition.workspace = true
readme = "README.md"
description = "QUIC connection APIs for decentralized endpoint connectivity"
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
rust-version.workspace = true

[dependencies]
qbase.workspace = true
qconnection.workspace = true
qprotocol.workspace = true
qresolve.workspace = true
qtls.workspace = true
qtransport.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "io-util", "signal"] }
